L515:
  fovy: 45
  w: 320
  h: 180

Large_L515:
  fovy: 45
  w: 640
  h: 360

D435:
  fovy: 37
  w: 320
  h: 240

Large_D435:
  fovy: 37
  w: 640
  h: 480

Modified_D435:
  fovy: 60
  w: 1280
  h: 720